### ISSUE TITLE
plano.emit_json() has NameError

### ISSUE THREAD

**Issue by kpvdr** [ssorj/plano#1]
Using plano.emit_json results in an error:
```
>>> plano.emit_json([1,2,3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kvdr/RedHat/plano/python/plano.py", line 339, in emit_json
    return _json.dumps(obj, f, indent=4, separators=(",", ": "), sort_keys=True)
NameError: name 'f' is not defined
```
A suggested fix is as follows:
```
diff --git a/python/plano.py b/python/plano.py
index 6449013..66830f0 100644
--- a/python/plano.py
+++ b/python/plano.py
@@ -336,7 +336,7 @@ def parse_json(json):
     return _json.loads(json)
 
 def emit_json(obj):
-    return _json.dumps(obj, f, indent=4, separators=(",", ": "), sort_keys=True)
+    return _json.dumps(obj, indent=4, separators=(",", ": "), sort_keys=True)
 
 def http_get(url, output_file=None, insecure=False):
     options = [
```
This fix is needed for the artifact poller.

**Comment by ssorj** [comment]
Now fixed
